// Code generated by hertz generator.

package main

import (
	"Dousheng_Backend/middleware"
	"Dousheng_Backend/utils/jwt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/pprof"
)

func initHertzWithMiddlewares(r *server.Hertz) {
	// 初始化自定义Register
	r.Use(
		middleware.TokenAuthMiddleware(*jwt.NewJWT(),
			"/douyin/user/register/", "/douyin/user/login/", "/douyin/feed/"), // 用户鉴权中间件
		middleware.AccessLog(),
		gzip.Gzip(gzip.DefaultCompression),
	)
}

func main() {
	h := server.Default()
	pprof.Register(h, "dev/pprof")
	// 初始化Hertz框架的全局路由等中间件
	initHertzWithMiddlewares(h)

	register(h)
	h.Spin()
}
